### PR TITLE
Fix image names in CI workflows

### PR DESCRIPTION
**Pull request by mhidalgo-bdai**
Follow-up to #48. What `snok/container-retention-policy@v2` refers to as "image-names" is actually "package-names" :roll_eyes: Third's the charm.

### CODE REVIEW

**Comment by mhidalgo-bdai** [comment]
```
ERROR: failed to solve: failed to push ghcr.io/bdaiinstitute/ros_utilities_jammy_humble:pr-51: failed commit on ref "manifest-sha256:1127d0daf00740d75dc22a4954ba6c10ddf7d20898ebeda1a40099957124635a": unexpected status from PUT request to https://ghcr.io/v2/bdaiinstitute/ros_utilities_jammy_humble/manifests/sha256:1127d0daf00740d75dc22a4954ba6c10ddf7d20898ebeda1a40099957124635a: 403 Forbidden
```

Hmm, do we need org authorization @amessing-bdai ?

**Review by jbarry-bdai — COMMENTED** [review]
Do we know why CI is upset?

**Comment by amessing-bdai** [comment]
Think it was just a network issue or something. Reran and its good.

**Review by amessing-bdai — APPROVED** [review]

**Comment by mhidalgo-bdai** [comment]
Uh. It was a 403 code. Odd.

Oh well, thanks for re-running Andrew.

**Pull request merged**
