### PR TITLE
Unit Testing

### PR DESCRIPTION
**Pull request by mpickett-bdai**
Unit test for the rest of the ROS Utilities that did not have any. Most are pretty straight forward, but some required a little multi-threading to get them to properly test the pathways. Let me know if anything is not commented enough or confusing. 

Jira Tickets: 
https://theaiinstitute.atlassian.net/browse/SW-223 and all the sub tickets

Suggested testing: 
Try running these unit tests locally. It'll be good to test that the threading works on other machines. I'm relying on some sleeping to help cause certain clashes, which is not very reliable, but probably fine for a unit test. 

Let me know if there's any issues or style things that I'm missing. I can also break up or squash the commits more.

### CODE REVIEW

**Comment by mpickett-bdai** [comment]
Forgot to run the pre-checks will address those shortly

**Comment by mpickett-bdai** [comment]
Pre-commit is fixed now, but CI doesn't seem to have the basic ros example services that I used for testing. I've seen us use it elsewhere at least in https://github.com/bdaiinstitute/bdai/pull/380 and it's a part of our normal docker image.

**Comment by amessing-bdai** [comment]
Fun. Apparently, this repo is using the docker image from spot_ros2. Probably should copy that one over, make a workflow to build it (can also be copied from spot_ros2), update it, and then use that instead.

**Review by amessing-bdai — APPROVED** [review]
LGTM

**Pull request merged**
